import React,{useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Pause,Play,ArrowDown} from 'lucide-react';
export default function Cinema({enquire,headline,intro,poster}){
 const section=useRef(),mount=useRef(),progress=useRef(0),paused=useRef(false);const[act,setAct]=useState(0),[ready,setReady]=useState(false),[failed,setFailed]=useState(false),[pause,setPause]=useState(false);
 useEffect(()=>{const root=section.current;const scroll=()=>{const r=root.getBoundingClientRect();progress.current=Math.max(0,Math.min(1,-r.top/(root.offsetHeight-innerHeight)));root.style.setProperty('--journey',progress.current);setAct(progress.current<.32?0:progress.current<.68?1:2)};scroll();window.addEventListener('scroll',scroll,{passive:true});return()=>window.removeEventListener('scroll',scroll)},[]);
 useEffect(()=>{let dead=false,frame,renderer,observer,visible=true;const disposables=[];let announced=false;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;paused.current=reduced;setPause(reduced);
 import('three').then(async T=>{
 if(dead)return;const {RoundedBoxGeometry}=await import('three/addons/geometries/RoundedBoxGeometry.js');if(dead)return;const host=mount.current;try{renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});}catch{setFailed(true);return}
 renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?1.3:1.7));renderer.setClearColor(0x111c22);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;renderer.shadowMap.enabled=innerWidth>700;renderer.shadowMap.type=T.PCFSoftShadowMap;host.appendChild(renderer.domElement);
 const scene=new T.Scene();scene.fog=new T.FogExp2(0x27383b,.009);const camera=new T.PerspectiveCamera(48,1,.1,180);const world=new T.Group();scene.add(world);
 const skyGeo=new T.SphereGeometry(110,32,16);const skyMat=new T.ShaderMaterial({side:T.BackSide,uniforms:{},vertexShader:'varying vec3 v;void main(){v=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 v;void main(){float h=clamp(normalize(v).y,0.,1.);vec3 c=mix(vec3(.56,.39,.24),vec3(.035,.085,.12),pow(h,.5));gl_FragColor=vec4(c,1.);}'});scene.add(new T.Mesh(skyGeo,skyMat));disposables.push(skyGeo,skyMat);
 scene.add(new T.HemisphereLight(0xa5c8dc,0x312d22,2.1));const sun=new T.DirectionalLight(0xffd09b,4);sun.position.set(-15,18,-12);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-20;sun.shadow.camera.right=20;sun.shadow.camera.top=20;sun.shadow.camera.bottom=-20;scene.add(sun);
 const mat=(color,roughness=.7,metalness=0)=>{const m=new T.MeshStandardMaterial({color,roughness,metalness});disposables.push(m);return m};const stone=mat(0xc7bda7),wood=mat(0x665640),dark=mat(0x182323,.4,.4),linen=mat(0xf5edda),olive=mat(0x4e6250),brass=mat(0xbb9160,.22,.7);
 function box(w,h,d,x,y,z,m){const g=m===linen?new RoundedBoxGeometry(w,h,d,3,Math.min(h/3,.09)):new T.BoxGeometry(w,h,d);disposables.push(g);const mesh=new T.Mesh(g,m);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;world.add(mesh);return mesh}
 // A deliberately open architectural set: the camera can travel from lake to room.
 box(16,.6,11,0,-.05,0,dark);box(14,.25,9,0,.4,0,stone);box(13,4.6,.25,0,2.65,-4,wood);box(.25,4.6,8,-6.4,2.65,0,stone);box(13.6,.3,8.5,0,5,0,dark);
 for(let x=-6;x<=6;x+=3)box(.13,4.5,.13,x,2.65,3.8,brass);
 for(let x=-5.8;x<=-2.4;x+=.26)box(.055,4.2,.09,x,2.6,-3.8,brass);
 const glow=new T.MeshStandardMaterial({color:0xffe4b0,emissive:0xffbb65,emissiveIntensity:3});disposables.push(glow);box(12.5,.04,.08,0,4.78,-3.65,glow);box(12.5,.03,.06,0,.6,3.95,glow);
 box(4.1,.18,3.6,1.8,.73,-.75,dark);box(3.9,.4,3.45,1.8,1,-.75,linen);box(4.1,1.45,.17,1.8,1.2,-2.48,olive);box(3.95,.09,1.05,1.8,1.25,.37,olive);
 for(const x of [.85,2.75]){const p=box(1.65,.25,.75,x,1.34,-1.73,linen);p.rotation.x=-.14}
 for(const x of [-.9,4.55]){box(.9,.75,.9,x,.96,-1.7,wood);box(.06,.75,.06,x,1.7,-1.7,brass);const g=new T.CylinderGeometry(.32,.48,.55,24);disposables.push(g);const lamp=new T.Mesh(g,linen);lamp.position.set(x,2.1,-1.7);world.add(lamp);const light=new T.PointLight(0xffc680,20,6,2);light.position.set(x,2,-1.4);world.add(light)}
 box(5.5,.035,5,1.6,.55,-.1,mat(0x9d9581));
 // Lounge and a sculptural stone table in the foreground.
 box(2.5,.6,1.1,-4,1,1,linen);box(2.5,.9,.22,-4,1.35,.4,linen);box(.22,.8,1.25,-5.2,1.15,1,olive);box(.22,.8,1.25,-2.8,1.15,1,olive);
 const tableG=new T.CylinderGeometry(.8,.65,.42,32);disposables.push(tableG);const table=new T.Mesh(tableG,stone);table.position.set(-3.8,.9,2.6);world.add(table);
 // Reflective water with animated ripples, kept procedural and asset-free.
 const waterG=new T.PlaneGeometry(180,180);const waterM=new T.ShaderMaterial({uniforms:{time:{value:0}},vertexShader:'varying vec2 uvv;void main(){uvv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 uvv;uniform float time;void main(){float r=sin(uvv.y*600.+sin(uvv.x*80.+time*.25)*3.+time*.4)*.5+.5;float shine=pow(max(0.,1.-abs(uvv.x-.45)*5.),8.)*(.15+.25*r);vec3 c=mix(vec3(.035,.09,.105),vec3(.12,.19,.19),uvv.y)+vec3(.5,.32,.13)*shine;gl_FragColor=vec4(c,1.);}'});const water=new T.Mesh(waterG,waterM);water.rotation.x=-Math.PI/2;water.position.y=-.55;scene.add(water);disposables.push(waterG,waterM);
 // Distant alpine silhouettes.
 const ridgeG=new T.PlaneGeometry(180,55,100,32),verts=ridgeG.attributes.position;for(let i=0;i<verts.count;i++){const x=verts.getX(i),d=verts.getY(i);const h=3+Math.abs(Math.sin(x*.065+.5)*6+Math.sin(x*.21+d*.09)*2.8+Math.sin(x*.47+d*.17)*1.1)+Math.sin(d*.13)*2;verts.setZ(i,h*Math.pow(Math.max(0,Math.sin((d+27.5)/55*Math.PI)),.7))}ridgeG.computeVertexNormals();const ridge=new T.Mesh(ridgeG,mat(0x415a5a));ridge.rotation.x=-Math.PI/2;ridge.position.set(0,-1,-58);scene.add(ridge);disposables.push(ridgeG);

 const pointsG=new T.BufferGeometry(),positions=new Float32Array(240*3);for(let i=0;i<positions.length;i+=3){positions[i]=(Math.random()-.5)*35;positions[i+1]=Math.random()*10;positions[i+2]=(Math.random()-.5)*25}pointsG.setAttribute('position',new T.BufferAttribute(positions,3));const pointsM=new T.PointsMaterial({color:0xffd7a0,size:.035,transparent:true,opacity:.5,depthWrite:false});const dust=new T.Points(pointsG,pointsM);scene.add(dust);disposables.push(pointsG,pointsM);
 const aim=new T.Vector3(),position=new T.Vector3();let smooth=0,time=0,last=0,mx=0,my=0;const pointer=e=>{mx=(e.clientX/innerWidth-.5);my=e.clientY/innerHeight-.5};window.addEventListener('pointermove',pointer,{passive:true});
 const resize=()=>{renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix()};observer=new ResizeObserver(resize);observer.observe(host);resize();
 const visibility=()=>{visible=!document.hidden};document.addEventListener('visibilitychange',visibility);
 function render(ms){if(dead)return;frame=requestAnimationFrame(render);if(!visible||section.current.getBoundingClientRect().bottom<0)return;const dt=Math.min((ms-last)/1000,.05);last=ms;if(!paused.current)time+=dt;smooth+=(progress.current-smooth)*(reduced?1:.055);const p=reduced?0:smooth;
 const mobile=innerWidth<700;const t=Math.min(p/.55,1),u=Math.max(0,(p-.55)/.45);position.set(T.MathUtils.lerp(mobile?17:19,5,t),T.MathUtils.lerp(mobile?10:9,3.2,t),T.MathUtils.lerp(mobile?30:24,10,t));position.lerp(new T.Vector3(1.8,2.6,4.3),u);aim.set(T.MathUtils.lerp(-1,1.5,p),1.8,T.MathUtils.lerp(0,-1.2,p));if(!paused.current){position.x+=Math.sin(time*.14)*.65+mx*.5;position.y+=Math.sin(time*.2)*.12-my*.2;waterM.uniforms.time.value=time;dust.rotation.y=time*.012}camera.position.copy(position);camera.lookAt(aim);renderer.render(scene,camera);if(!announced){announced=true;setReady(true)}}frame=requestAnimationFrame(render);
 disposables.push(()=>window.removeEventListener('pointermove',pointer),()=>document.removeEventListener('visibilitychange',visibility));
 }).catch(()=>setFailed(true));return()=>{dead=true;cancelAnimationFrame(frame);observer?.disconnect();renderer?.dispose();renderer?.domElement.remove();disposables.forEach(x=>typeof x==='function'?x():x.dispose())}},[]);
 const titles=[<>{headline==='The art of arriving home.'?<>Some places<br/>stay <i>with you.</i></>:headline}</>,<>Before the world<br/>arrives. <i>We do.</i></>,<>Every detail.<br/><i>Beautifully ready.</i></>];
 return <section className={'cinema '+(pause?'motion-paused':'')} ref={section} aria-label="A cinematic journey through an illustrative alpine residence"><div className="cinema-stage" style={!ready?{backgroundImage:`linear-gradient(90deg,#06110fbf,#06110f44),url(${poster})`,backgroundSize:'cover',backgroundPosition:'center'}:undefined}><div className={'cinema-world '+(ready?'is-ready':'')} ref={mount}/><div className="cinema-vignette"/><div className="cinema-grain"/><div className="cinema-top"><span>AN EXERCISE IN EXCEPTIONAL CARE</span><span>WĀNAKA · NEW ZEALAND</span></div><div className="cinema-copy" key={act}><span className="eyebrow">K–BOOM KLEEN / {['THE ARRIVAL','THE QUIET WORK','THE WELCOME'][act]}</span><h1>{titles[act]}</h1><p>{[intro,'A room reset. Linen laid with intention. The quiet work behind a remarkable first impression.','Short-stay turnovers, deep cleaning and linen preparation. Thoughtful care for your next chapter.'][act]}</p><button className="button light" onClick={enquire}>Arrange your property’s care <ArrowUpRight size={18}/></button></div><div className="cinema-side">THE ART OF ARRIVING HOME</div><div className="cinema-bottom"><a href="#philosophy">{act===2?'EXPLORE OUR CARE':'SCROLL TO ENTER'} <ArrowDown size={16}/></a><div className="act-meter">{['ARRIVE','DISCOVER','FEEL AT HOME'].map((s,i)=><span key={s} className={i===act?'current':''}><b>0{i+1}</b>{s}</span>)}</div><button className="motion-toggle" onClick={()=>{paused.current=!paused.current;setPause(paused.current)}} aria-label={pause?'Play ambient motion':'Pause ambient motion'}>{pause?<Play size={14}/>:<Pause size={14}/>}</button></div><div className="journey-track"><span/></div><span className="scene-disclosure">{failed?'STATIC PRESENTATION · ':''}IMAGINED RESIDENCE · 3D BRAND FILM</span></div></section>
}
