import React,{useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{motion,AnimatePresence,useScroll,useTransform}from'framer-motion';
import{ArrowUpRight,Check,Phone,Mail,Menu,X,Sparkles,ChevronDown,Minus,Plus,MapPin,Clock3,ShieldCheck,Home,Quote}from'lucide-react';
import'./styles.css';
const E=[.16,1,.3,1],areas=['Wānaka','Albert Town','Lake Hāwea','Luggate'];
const groups=[
['Property & rooms',[['Bedrooms',5],['Master Bedroom',5],['Living Room / Lounge',5],['Dining Room',5],['Kitchen',30],['Butler Pantry / Scullery',5],['Laundry',5],['Hallways',5],['Stairs',5],['Entry / Foyer',5],['Office / Study',5],['Games / Media Room',10],['Garage',5],['Balcony / Deck',5],['Outdoor BBQ Area',10],['Storage Room',5],['Other Room / Area',0]]],
['Beds',[['King Bed',15],['Queen Bed',15],['Single Bed',15],['Bunk Bed Set',30],['Couch/Sofa Bed',15]]],
['Bathroom & toilet',[['Bathroom',5],['Separate Toilet',5],['Powder Room',5],['Shower',10],['Bathtub',7],['Double Vanity',6],['Spa / Tub Area',7]]],
['Extra services',[['Oven Interior',30],['Rangehood / Filters',30],['Interior Windows',5],['Exterior Windows',5],['Tracks / Frames',5],['Carpet Shampoo',20],['Wall Spot Cleaning',10],['Skirting / Door Frames',5],['BBQ Clean',30],['Outdoor Furniture Wipe',40],['Other',0]]]
];
function Logo(){return <a className="logo" href="#top"><i>✦</i><span>K-BOOM<b>KLEEN</b></span></a>}
function Header(){const[o,setO]=useState(false);return <header><Logo/><nav><a href="#services">Services</a><a href="#estimator">Instant quote</a><a href="#standard">Our standard</a><a href="#areas">Areas</a></nav><a href="#estimator" className="navcta">Estimate my clean <ArrowUpRight/></a><button className="hamb" onClick={()=>setO(!o)}>{o?<X/>:<Menu/>}</button><AnimatePresence>{o&&<motion.div className="mobile" initial={{opacity:0,y:-20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-20}}><a href="#services" onClick={()=>setO(false)}>Services</a><a href="#estimator" onClick={()=>setO(false)}>Instant quote</a><a href="#standard" onClick={()=>setO(false)}>Our standard</a><a href="#areas" onClick={()=>setO(false)}>Areas</a></motion.div>}</AnimatePresence></header>}
function Hero(){const{scrollY}=useScroll(),y=useTransform(scrollY,[0,800],[0,180]);return <section className="hero" id="top"><div className="grain"/><motion.div className="orb" style={{y}}/><div className="heroCopy"><motion.div initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.8,ease:E}} className="kicker"><span/> Wānaka property care</motion.div><motion.h1 initial={{opacity:0,y:45}} animate={{opacity:1,y:0}} transition={{duration:1,ease:E,delay:.1}}>Clean that<br/><em>checks in.</em></motion.h1><motion.p initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.45}}>Turnovers, deep cleans and linen care for homes that need to feel exceptional the second the door opens.</motion.p><motion.div className="heroBtns" initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:.6}}><a className="primary" href="#estimator">Build my instant estimate <ArrowUpRight/></a><a className="ghost" href="#services">Explore K-Boom ↓</a></motion.div></div><motion.div className="stage" initial={{opacity:0,scale:.9}} animate={{opacity:1,scale:1}} transition={{duration:1.2,ease:E}}><div className="stagePhoto"><div className="photoOverlay"><span>01 / WĀNAKA</span><b>Arrival-ready<br/>is the standard.</b></div></div><motion.div className="cleanCard" animate={{y:[0,-12,0],rotate:[-3,-1,-3]}} transition={{duration:5,repeat:Infinity}}><span className="check"><Check/></span><div><small>TURNOVER STATUS</small><b>Fresh. Reset. Ready.</b></div></motion.div><motion.div className="rateCard" animate={{y:[0,10,0]}} transition={{duration:5.5,repeat:Infinity}}><small>ESTIMATE FROM</small><strong>$55<sup>/hr</sup></strong><span>+ GST</span></motion.div></motion.div><div className="marquee"><div>SHORT-STAY CLEANING ✦ DEEP CLEANING ✦ LINEN SERVICE ✦ WĀNAKA ✦ ALBERT TOWN ✦ LAKE HĀWEA ✦ LUGGATE ✦ SHORT-STAY CLEANING ✦ DEEP CLEANING ✦ LINEN SERVICE ✦</div></div></section>}
const svc=[['01','Short-stay','Turnover cleaning that respects the clock and obsesses over the arrival moment.','HOST MODE'],['02','Deep clean','A deliberate top-to-bottom reset when your property needs more than a quick refresh.','RESET MODE'],['03','Linen care','Crisp, guest-ready linen support that removes one more thing from your hosting list.','FRESH MODE']];
function Services(){return <section className="services" id="services"><div className="intro"><span>THE K-BOOM EDIT</span><h2>Less “cleaning company.”<br/><em>More property ritual.</em></h2></div><div className="svcGrid">{svc.map((x,i)=><motion.article key={x[0]} initial={{opacity:0,y:50}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.12,duration:.8,ease:E}} whileHover={{y:-12}}><div className={'svcVisual v'+i}><span>{x[3]}</span><i>✦</i></div><div className="svcBody"><small>{x[0]}</small><h3>{x[1]}</h3><p>{x[2]}</p><a href="#estimator">Estimate this clean <ArrowUpRight/></a></div></motion.article>)}</div></section>}
function Counter({name,value,set}){return <div className="counter"><span>{name}</span><div><button onClick={()=>set(Math.max(0,value-1))}><Minus/></button><b>{value}</b><button onClick={()=>set(value+1)}><Plus/></button></div></div>}
function Estimator(){const[counts,setCounts]=useState({}),[tab,setTab]=useState(0);const mins=useMemo(()=>groups.flatMap(g=>g[1]).reduce((a,[n,m])=>a+(counts[n]||0)*m,0),[counts]);const raw=mins/60,hrs=Math.ceil(raw*4)/4,sub=hrs*55,gst=sub*.15,total=sub+gst;const selected=Object.values(counts).reduce((a,b)=>a+b,0);return <section className="estimate" id="estimator"><div className="estTop"><span>LIVE QUOTE ESTIMATOR</span><h2>Know your number.<br/><em>Before we even talk.</em></h2><p>Build your property below. Your estimate updates instantly using K-Boom’s cleaning-time model.</p></div><div className="estShell"><div className="builder"><div className="tabs">{groups.map((g,i)=><button className={tab===i?'active':''} onClick={()=>setTab(i)} key={g[0]}><span>0{i+1}</span>{g[0]}</button>)}</div><AnimatePresence mode="wait"><motion.div className="counterGrid" key={tab} initial={{opacity:0,x:30}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-20}} transition={{duration:.35}}>{groups[tab][1].map(([n])=><Counter key={n} name={n} value={counts[n]||0} set={v=>setCounts(c=>({...c,[n]:v}))}/>)}</motion.div></AnimatePresence><div className="estNav"><button disabled={tab===0} onClick={()=>setTab(tab-1)}>← Previous</button>{tab<3?<button className="next" onClick={()=>setTab(tab+1)}>Continue <ArrowUpRight/></button>:<a className="next" href="#book">Send estimate <ArrowUpRight/></a>}</div></div><motion.aside className="receipt" layout><div className="receiptHead"><div><small>YOUR LIVE ESTIMATE</small><b>{selected?selected:'—'} <span>items selected</span></b></div><Sparkles/></div><div className="price"><small>ESTIMATED TOTAL</small><strong>${total.toFixed(2)}</strong><span>NZD incl. GST</span></div><div className="breakdown"><p><span>Estimated time</span><b>{hrs.toFixed(2)} hrs</b></p><p><span>Rate</span><b>$55.00/hr</b></p><p><span>Subtotal</span><b>${sub.toFixed(2)}</b></p><p><span>GST (15%)</span><b>${gst.toFixed(2)}</b></p></div><div className="estimateNote"><Clock3/><p>Time is rounded up to the next 15-minute interval. This is an estimate only; final pricing may change after property-condition review.</p></div><a className="receiptCta" href="#book">Request this clean <ArrowUpRight/></a></motion.aside></div></section>}
function Standard(){return <section className="standard" id="standard"><div className="stdLeft"><span>NOT JUST SPOTLESS</span><h2>We clean for<br/><em>the first impression.</em></h2><p>A guest doesn’t see a checklist. They see the room, smell the fresh linen and decide how the stay feels.</p></div><div className="stdStack">{[[ShieldCheck,'A standard you can feel','Detail-led presentation, not a rushed checklist.'],[Clock3,'Built around arrivals','Turnover-aware service for time-sensitive properties.'],[Home,'Local accountability','Wānaka-area service with a direct point of contact.']].map(([I,t,p],i)=><motion.div key={t} initial={{opacity:0,x:50}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{delay:i*.13}}><span><I/></span><div><small>0{i+1}</small><h3>{t}</h3><p>{p}</p></div></motion.div>)}</div></section>}
function Areas(){return <section className="area" id="areas"><div className="areaCopy"><span>LOCAL BY DESIGN</span><h2>Four places.<br/><em>One standard.</em></h2><p>Property care across Wānaka and the communities around it.</p>{areas.map((a,i)=><motion.div className="areaRow" key={a} initial={{opacity:0,x:-20}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{delay:i*.08}}><b>0{i+1}</b><span>{a}</span><MapPin/></motion.div>)}</div><div className="mapArt"><div className="mapLake"/><div className="mapRing r1"/><div className="mapRing r2"/><div className="mapRing r3"/><span className="mapLabel">K-BOOM<br/>SERVICE<br/>RADIUS</span></div></section>}
function Book(){return <section className="book" id="book"><div><Quote/><span>LET’S MAKE IT FRESH</span><h2>Your next arrival<br/>starts <em>here.</em></h2><p>Send your details and we’ll confirm availability and the final cleaning scope.</p><div className="contacts"><a href="tel:0223489772"><Phone/>022 348 9772</a><a href="mailto:kboomkleen@gmail.com"><Mail/>kboomkleen@gmail.com</a></div></div><form onSubmit={e=>e.preventDefault()}><label>Your name<input required placeholder="Name"/></label><label>Phone or email<input required placeholder="Best contact"/></label><div className="form2"><label>Preferred date<input type="date"/></label><label>Area<select>{areas.map(x=><option key={x}>{x}</option>)}</select></label></div><label>Anything we should know?<textarea rows="4" placeholder="Property, access, linen or timing notes…"/></label><button>Request my clean <ArrowUpRight/></button><small>No payment required. We confirm availability first.</small></form></section>}
function Footer(){return <footer><Logo/><p>Guest-ready property care in Wānaka.</p><div><a href="#services">Services</a><a href="#estimator">Estimator</a><a href="#areas">Areas</a><a href="https://www.instagram.com/kboomkleen" target="_blank">Instagram ↗</a></div><span>© {new Date().getFullYear()} K-Boom Kleen</span></footer>}
function App(){return <><Header/><main><Hero/><Services/><Estimator/><Standard/><Areas/><Book/></main><Footer/><a className="floatCall" href="tel:0223489772"><Phone/> Call K-Boom</a></>};createRoot(document.getElementById('root')).render(<App/>);
